# Outlet definitions for PolitiScan
# STATE_OUTLETS: state name -> list of outlet dicts, each with "name" (display) and "domain" (real website domain)
# OUTLET_DOMAINS: outlet display name -> primary domain (kept for backward-compatible lookups)

STATE_OUTLETS = {
    "Andhra Pradesh": [
        {"name": "The Hindu",         "domain": "thehindu.com"},
        {"name": "NDTV",              "domain": "ndtv.com"},
        {"name": "Deccan Chronicle",  "domain": "deccanchronicle.com"},
        {"name": "Hans India",        "domain": "thehansindia.com"},
        {"name": "Andhra Jyothi",     "domain": "andhrajyothy.com"},
        {"name": "Eenadu",            "domain": "eenadu.net"},
        {"name": "Sakshi",            "domain": "sakshi.com"},
        {"name": "TV9 Telugu",        "domain": "tv9telugu.com"},
        {"name": "ABN Andhra Jyothi", "domain": "abnnews.in"},
    ],
    "Arunachal Pradesh": [
        {"name": "NDTV",            "domain": "ndtv.com"},
        {"name": "The Hindu",       "domain": "thehindu.com"},
        {"name": "Arunachal Times", "domain": "arunachaltimes.in"},
        {"name": "Arunachal Front", "domain": "arunachalfront.com"},
        {"name": "The Sentinel",    "domain": "sentinelassam.com"},
        {"name": "Northeast Now",   "domain": "nenow.in"},
        {"name": "EastMojo",        "domain": "eastmojo.com"},
        {"name": "Morung Express",  "domain": "morungexpress.com"},
    ],
    "Assam": [
        {"name": "The Hindu",      "domain": "thehindu.com"},
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "The Sentinel",   "domain": "sentinelassam.com"},
        {"name": "Assam Tribune",  "domain": "assamtribune.com"},
        {"name": "Northeast Now",  "domain": "nenow.in"},
        {"name": "EastMojo",       "domain": "eastmojo.com"},
        {"name": "Pratidin Time",  "domain": "pratidintime.com"},
        {"name": "News Live Assam","domain": "newslive.in"},
        {"name": "G Plus",         "domain": "guwahatiplus.com"},
    ],
    "Bihar": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "Hindustan Times","domain": "hindustantimes.com"},
        {"name": "Times of India", "domain": "timesofindia.com"},
        {"name": "Hindustan",      "domain": "livehindustan.com"},
        {"name": "Dainik Jagran",  "domain": "jagran.com"},
        {"name": "Dainik Bhaskar", "domain": "bhaskar.com"},
        {"name": "Prabhat Khabar", "domain": "prabhatkhabar.com"},
        {"name": "News18",         "domain": "news18.com"},
    ],
    "Chhattisgarh": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "Times of India", "domain": "timesofindia.com"},
        {"name": "Dainik Jagran",  "domain": "jagran.com"},
        {"name": "Dainik Bhaskar", "domain": "bhaskar.com"},
        {"name": "Nai Dunia",      "domain": "naidunia.com"},
        {"name": "Haribhoomi",     "domain": "haribhoomi.com"},
        {"name": "IBC24",          "domain": "ibc24.in"},
        {"name": "ETV Bharat",     "domain": "etvbharat.com"},
    ],
    "Goa": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "Times of India", "domain": "timesofindia.com"},
        {"name": "Herald Goa",     "domain": "heraldgoa.in"},
        {"name": "Navhind Times",  "domain": "navhindtimes.in"},
        {"name": "Gomantak",       "domain": "gomantak.com"},
        {"name": "Prudent Media",  "domain": "prudentmedia.in"},
        {"name": "Goa365",         "domain": "goa365tv.com"},
        {"name": "O Heraldo",      "domain": "heraldo.in"},
    ],
    "Gujarat": [
        {"name": "NDTV",            "domain": "ndtv.com"},
        {"name": "Times of India",  "domain": "timesofindia.com"},
        {"name": "Indian Express",  "domain": "indianexpress.com"},
        {"name": "Divya Bhaskar",   "domain": "divyabhaskar.co.in"},
        {"name": "Gujarat Samachar","domain": "gujaratsamachar.com"},
        {"name": "Sandesh",         "domain": "sandesh.com"},
        {"name": "TV9 Gujarati",    "domain": "tv9gujarati.com"},
        {"name": "Zee 24 Kalak",    "domain": "zee24kalak.com"},
    ],
    "Haryana": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "Hindustan Times","domain": "hindustantimes.com"},
        {"name": "Times of India", "domain": "timesofindia.com"},
        {"name": "Dainik Jagran",  "domain": "jagran.com"},
        {"name": "Dainik Bhaskar", "domain": "bhaskar.com"},
        {"name": "Punjab Kesari",  "domain": "punjabkesari.in"},
        {"name": "Amar Ujala",     "domain": "amarujala.com"},
        {"name": "Tribune India",  "domain": "tribuneindia.com"},
    ],
    "Himachal Pradesh": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "Hindustan Times","domain": "hindustantimes.com"},
        {"name": "Tribune India",  "domain": "tribuneindia.com"},
        {"name": "Dainik Jagran",  "domain": "jagran.com"},
        {"name": "Dainik Bhaskar", "domain": "bhaskar.com"},
        {"name": "Divya Himachal", "domain": "divyahimachal.com"},
        {"name": "Amar Ujala",     "domain": "amarujala.com"},
        {"name": "ETV Bharat",     "domain": "etvbharat.com"},
    ],
    "Jharkhand": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "Times of India", "domain": "timesofindia.com"},
        {"name": "Hindustan Times","domain": "hindustantimes.com"},
        {"name": "Dainik Jagran",  "domain": "jagran.com"},
        {"name": "Dainik Bhaskar", "domain": "bhaskar.com"},
        {"name": "Prabhat Khabar", "domain": "prabhatkhabar.com"},
        {"name": "News18",         "domain": "news18.com"},
        {"name": "ETV Bharat",     "domain": "etvbharat.com"},
    ],
    "Karnataka": [
        {"name": "The Hindu",       "domain": "thehindu.com"},
        {"name": "Deccan Herald",   "domain": "deccanherald.com"},
        {"name": "Indian Express",  "domain": "indianexpress.com"},
        {"name": "NDTV",            "domain": "ndtv.com"},
        {"name": "Vijaya Karnataka","domain": "vijaykarnataka.com"},
        {"name": "Prajavani",       "domain": "prajavani.net"},
        {"name": "Udayavani",       "domain": "udayavani.com"},
        {"name": "TV9 Kannada",     "domain": "tv9kannada.com"},
        {"name": "Kannada Prabha",  "domain": "kannadaprabha.com"},
    ],
    "Kerala": [
        {"name": "The Hindu",         "domain": "thehindu.com"},
        {"name": "Indian Express",    "domain": "indianexpress.com"},
        {"name": "NDTV",              "domain": "ndtv.com"},
        {"name": "Mathrubhumi",       "domain": "mathrubhumi.com"},
        {"name": "Malayala Manorama", "domain": "manoramaonline.com"},
        {"name": "Asianet News",      "domain": "asianetnews.com"},
        {"name": "MediaOne",          "domain": "mediaoneindia.com"},
        {"name": "Manorama News",     "domain": "manoramaonline.com"},
        {"name": "Reporter Live",     "domain": "reporterlive.com"},
    ],
    "Madhya Pradesh": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "Times of India", "domain": "timesofindia.com"},
        {"name": "Dainik Jagran",  "domain": "jagran.com"},
        {"name": "Dainik Bhaskar", "domain": "bhaskar.com"},
        {"name": "Nai Dunia",      "domain": "naidunia.com"},
        {"name": "Patrika",        "domain": "patrika.com"},
        {"name": "Nava Dunia",     "domain": "navadunia.com"},
        {"name": "ETV Bharat",     "domain": "etvbharat.com"},
    ],
    "Maharashtra": [
        {"name": "Indian Express",   "domain": "indianexpress.com"},
        {"name": "Times of India",   "domain": "timesofindia.com"},
        {"name": "NDTV",             "domain": "ndtv.com"},
        {"name": "Hindustan Times",  "domain": "hindustantimes.com"},
        {"name": "Loksatta",         "domain": "loksatta.com"},
        {"name": "Maharashtra Times","domain": "maharashtratimes.indiatimes.com"},
        {"name": "Lokmat",           "domain": "lokmat.com"},
        {"name": "Zee 24 Taas",      "domain": "zeenews.india.com"},
        {"name": "ABP Majha",        "domain": "abpmajha.abplive.com"},
    ],
    "Manipur": [
        {"name": "NDTV",            "domain": "ndtv.com"},
        {"name": "The Hindu",       "domain": "thehindu.com"},
        {"name": "Sangai Express",  "domain": "e-pao.net"},
        {"name": "Imphal Free Press","domain": "ifp.co.in"},
        {"name": "Morung Express",  "domain": "morungexpress.com"},
        {"name": "EastMojo",        "domain": "eastmojo.com"},
        {"name": "Northeast Now",   "domain": "nenow.in"},
        {"name": "E-Pao",           "domain": "e-pao.net"},
    ],
    "Meghalaya": [
        {"name": "NDTV",               "domain": "ndtv.com"},
        {"name": "The Hindu",          "domain": "thehindu.com"},
        {"name": "Shillong Times",     "domain": "theshillongtimes.com"},
        {"name": "Meghalaya Guardian", "domain": "meghalayaguardian.com"},
        {"name": "Northeast Now",      "domain": "nenow.in"},
        {"name": "EastMojo",           "domain": "eastmojo.com"},
        {"name": "Morung Express",     "domain": "morungexpress.com"},
        {"name": "Northeast Today",    "domain": "northeasttoday.in"},
    ],
    "Mizoram": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "The Hindu",      "domain": "thehindu.com"},
        {"name": "Vanglaini",      "domain": "vanglaini.org"},
        {"name": "Aizawl Post",    "domain": "aizawlpost.com"},
        {"name": "EastMojo",       "domain": "eastmojo.com"},
        {"name": "Northeast Now",  "domain": "nenow.in"},
        {"name": "Morung Express", "domain": "morungexpress.com"},
        {"name": "Millennium Post","domain": "millenniumpost.in"},
    ],
    "Nagaland": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "The Hindu",      "domain": "thehindu.com"},
        {"name": "Nagaland Post",  "domain": "nagalandpost.com"},
        {"name": "Morung Express", "domain": "morungexpress.com"},
        {"name": "EastMojo",       "domain": "eastmojo.com"},
        {"name": "Northeast Now",  "domain": "nenow.in"},
        {"name": "Eastern Mirror", "domain": "easternmirrornagaland.com"},
        {"name": "The Sentinel",   "domain": "sentinelassam.com"},
    ],
    "Odisha": [
        {"name": "The Hindu",    "domain": "thehindu.com"},
        {"name": "NDTV",         "domain": "ndtv.com"},
        {"name": "Times of India","domain": "timesofindia.com"},
        {"name": "Sambad",       "domain": "sambad.com"},
        {"name": "Dharitri",     "domain": "dharitri.com"},
        {"name": "Pragativadi",  "domain": "pragativadi.com"},
        {"name": "OTV",          "domain": "odishatv.in"},
        {"name": "Odisha TV",    "domain": "odishatv.in"},
        {"name": "Kanak News",   "domain": "kanakodisha.com"},
    ],
    "Punjab": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "Hindustan Times","domain": "hindustantimes.com"},
        {"name": "Tribune India",  "domain": "tribuneindia.com"},
        {"name": "Times of India", "domain": "timesofindia.com"},
        {"name": "Dainik Jagran",  "domain": "jagran.com"},
        {"name": "Punjab Kesari",  "domain": "punjabkesari.in"},
        {"name": "Dainik Bhaskar", "domain": "bhaskar.com"},
        {"name": "Jagbani",        "domain": "jagbani.punjabkesari.in"},
    ],
    "Rajasthan": [
        {"name": "NDTV",              "domain": "ndtv.com"},
        {"name": "Times of India",    "domain": "timesofindia.com"},
        {"name": "Dainik Jagran",     "domain": "jagran.com"},
        {"name": "Dainik Bhaskar",    "domain": "bhaskar.com"},
        {"name": "Rajasthan Patrika", "domain": "patrika.com"},
        {"name": "Navbharat Times",   "domain": "navbharattimes.indiatimes.com"},
        {"name": "Amar Ujala",        "domain": "amarujala.com"},
        {"name": "ETV Bharat",        "domain": "etvbharat.com"},
    ],
    "Sikkim": [
        {"name": "NDTV",               "domain": "ndtv.com"},
        {"name": "The Hindu",          "domain": "thehindu.com"},
        {"name": "Sikkim Express",     "domain": "sikkimexpress.com"},
        {"name": "EastMojo",           "domain": "eastmojo.com"},
        {"name": "Northeast Now",      "domain": "nenow.in"},
        {"name": "The Statesman",      "domain": "thestatesman.com"},
        {"name": "Northeast Today",    "domain": "northeasttoday.in"},
        {"name": "Himalayan Mewsline", "domain": "himalayanmewsline.com"},
    ],
    "Tamil Nadu": [
        {"name": "The Hindu",           "domain": "thehindu.com"},
        {"name": "Indian Express",      "domain": "indianexpress.com"},
        {"name": "NDTV",                "domain": "ndtv.com"},
        {"name": "Dinamalar",           "domain": "dinamalar.com"},
        {"name": "Dinamani",            "domain": "dinamani.com"},
        {"name": "Daily Thanthi",       "domain": "dailythanthi.com"},
        {"name": "Puthiya Thalaimurai", "domain": "puthiyathalaimurai.tv"},
        {"name": "Sun News",            "domain": "sunnewsonline.com"},
        {"name": "Polimer News",        "domain": "polimernews.com"},
    ],
    "Telangana": [
        {"name": "The Hindu",       "domain": "thehindu.com"},
        {"name": "NDTV",            "domain": "ndtv.com"},
        {"name": "Deccan Chronicle","domain": "deccanchronicle.com"},
        {"name": "Hans India",      "domain": "thehansindia.com"},
        {"name": "Eenadu",          "domain": "eenadu.net"},
        {"name": "Sakshi",          "domain": "sakshi.com"},
        {"name": "TV9 Telugu",      "domain": "tv9telugu.com"},
        {"name": "V6 News",         "domain": "v6news.tv"},
        {"name": "Telangana Today", "domain": "telanganatoday.com"},
    ],
    "Tripura": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "The Hindu",      "domain": "thehindu.com"},
        {"name": "Dainik Sambad",  "domain": "dainiktripurabarta.com"},
        {"name": "Tripura Tribune","domain": "tripuratribune.com"},
        {"name": "Northeast Now",  "domain": "nenow.in"},
        {"name": "EastMojo",       "domain": "eastmojo.com"},
        {"name": "The Sentinel",   "domain": "sentinelassam.com"},
        {"name": "Agartala Today", "domain": "agartalatoday.com"},
    ],
    "Uttar Pradesh": [
        {"name": "NDTV",            "domain": "ndtv.com"},
        {"name": "Hindustan Times", "domain": "hindustantimes.com"},
        {"name": "Times of India",  "domain": "timesofindia.com"},
        {"name": "Dainik Jagran",   "domain": "jagran.com"},
        {"name": "Dainik Bhaskar",  "domain": "bhaskar.com"},
        {"name": "Amar Ujala",      "domain": "amarujala.com"},
        {"name": "Navbharat Times", "domain": "navbharattimes.indiatimes.com"},
        {"name": "News18",          "domain": "news18.com"},
    ],
    "Uttarakhand": [
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "Hindustan Times","domain": "hindustantimes.com"},
        {"name": "Times of India", "domain": "timesofindia.com"},
        {"name": "Dainik Jagran",  "domain": "jagran.com"},
        {"name": "Dainik Bhaskar", "domain": "bhaskar.com"},
        {"name": "Amar Ujala",     "domain": "amarujala.com"},
        {"name": "Tribune India",  "domain": "tribuneindia.com"},
        {"name": "ETV Bharat",     "domain": "etvbharat.com"},
    ],
    "West Bengal": [
        {"name": "The Hindu",          "domain": "thehindu.com"},
        {"name": "Times of India",     "domain": "timesofindia.com"},
        {"name": "Hindustan Times",    "domain": "hindustantimes.com"},
        {"name": "NDTV",               "domain": "ndtv.com"},
        {"name": "Anandabazar Patrika","domain": "anandabazar.com"},
        {"name": "Aajkaal",            "domain": "aajkaal.in"},
        {"name": "Sangbad Pratidin",   "domain": "sangbadpratidin.in"},
        {"name": "ABP Ananda",         "domain": "abpananda.abplive.com"},
        {"name": "Zee 24 Ghanta",      "domain": "zee24ghanta.com"},
    ],
    "Delhi": [
        {"name": "Hindustan Times","domain": "hindustantimes.com"},
        {"name": "Times of India", "domain": "timesofindia.com"},
        {"name": "Indian Express", "domain": "indianexpress.com"},
        {"name": "NDTV",           "domain": "ndtv.com"},
        {"name": "The Hindu",      "domain": "thehindu.com"},
        {"name": "Navbharat Times","domain": "navbharattimes.indiatimes.com"},
        {"name": "Dainik Jagran",  "domain": "jagran.com"},
        {"name": "Amar Ujala",     "domain": "amarujala.com"},
        {"name": "India TV",       "domain": "indiatvnews.com"},
    ],
    "Jammu & Kashmir": [
        {"name": "NDTV",            "domain": "ndtv.com"},
        {"name": "Times of India",  "domain": "timesofindia.com"},
        {"name": "Greater Kashmir", "domain": "greaterkashmir.com"},
        {"name": "Kashmir Observer","domain": "kashmirobserver.net"},
        {"name": "Daily Excelsior", "domain": "dailyexcelsior.com"},
        {"name": "Kashmir Times",   "domain": "kashmirtimes.com"},
        {"name": "Rising Kashmir",  "domain": "risingkashmir.com"},
        {"name": "State Times",     "domain": "statetimes.in"},
    ],
    "Ladakh": [
        {"name": "NDTV",            "domain": "ndtv.com"},
        {"name": "The Hindu",       "domain": "thehindu.com"},
        {"name": "Daily Excelsior", "domain": "dailyexcelsior.com"},
        {"name": "Kashmir Times",   "domain": "kashmirtimes.com"},
        {"name": "Greater Kashmir", "domain": "greaterkashmir.com"},
        {"name": "Reach Ladakh",    "domain": "reachladakh.com"},
        {"name": "State Times",     "domain": "statetimes.in"},
        {"name": "ETV Bharat",      "domain": "etvbharat.com"},
    ],
    "Puducherry": [
        {"name": "The Hindu",        "domain": "thehindu.com"},
        {"name": "NDTV",             "domain": "ndtv.com"},
        {"name": "Indian Express",   "domain": "indianexpress.com"},
        {"name": "Dinamalar",        "domain": "dinamalar.com"},
        {"name": "Dinamani",         "domain": "dinamani.com"},
        {"name": "Daily Thanthi",    "domain": "dailythanthi.com"},
        {"name": "Puducherry Today", "domain": "puducherrytoday.in"},
        {"name": "Tamil Murasu",     "domain": "tamilmurasu.com.sg"},
    ],
}

# Build OUTLET_DOMAINS from STATE_OUTLETS for backward-compatible lookups.
# Entries that appear in multiple states keep whichever domain is listed last
# (all duplicates use the same domain, so this is safe).
OUTLET_DOMAINS: dict[str, str] = {}
for _outlets in STATE_OUTLETS.values():
    for _o in _outlets:
        OUTLET_DOMAINS[_o["name"]] = _o["domain"]

# Outlets with a direct native RSS feed URL.
# These are fetched from the source directly instead of via Google News site: query.
NATIVE_RSS_FEEDS: dict[str, str] = {
    "Prajavani":        "https://www.prajavani.net/stories.rss",
    "TV9 Kannada":      "https://tv9kannada.com/feed",
    "Vijaya Karnataka": "https://vijaykarnataka.com/rssfeedsdefault.cms",
    "Kannada Prabha":   "https://www.kannadaprabha.com/feed",
}
